version: 2
jobs:
  docs:
    working_directory: ~/misk-web/docs
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run-script build
  node:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Misk-Web Prebuild...
          command: sudo npm install -g @misk/cli && miskweb prebuild -e
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js update
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js rebuild --verbose
  java:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build Gradle Plugin
          command: ./gradlew plugin
workflows:
  version: 2
  commit:
    jobs:
      - node
      - java
      - docs
  continuous-testing:
    jobs:
      - node
      - java
      - docs
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
