version: 2
jobs:
  docs:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install
          command: cd docs && npm install
      - run:
          name: Build
          command: cd docs && npm run-script build
  node10LTS:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Misk-Web Prebuild...
          command: sudo npm install -g @misk/cli && miskweb prebuild -e
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js update
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js build --verbose
  node12_9:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - run:
          name: Misk-Web Prebuild...
          command: sudo npm install -g @misk/cli && miskweb prebuild -e
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js update
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js build --verbose
  new10LTS:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Misk-Web Install...
          command: sudo npm install -g @misk/cli
      - run:
          name: Create test directory...
          command: mkdir new-tab-ci-test && cd new-tab-ci-test
      - run:
          name: miskweb new...
          command: miskweb new "Alpha Bravo" "alpha-bravo"
  new12_9:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - run:
          name: Misk-Web Install...
          command: sudo npm install -g @misk/cli
      - run:
          name: Create test directory...
          command: mkdir new-tab-ci-test && cd new-tab-ci-test
      - run:
          name: miskweb new...
          command: miskweb new "Alpha Bravo" "alpha-bravo"
  java:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build Gradle Plugin
          command: ./gradlew plugin
workflows:
  version: 2
  commit:
    jobs:
      - node10LTS:
          filters:
            branches:
              ignore: gh-pages
      - node12_9:
          filters:
            branches:
              ignore: gh-pages
      - java:
          filters:
            branches:
              ignore: gh-pages
      - docs:
          filters:
            branches:
              ignore: gh-pages
      - new10LTS:
          filters:
            branches:
              ignore: gh-pages
      - new12_9:
          filters:
            branches:
              ignore: gh-pages
  continuous-testing:
    jobs:
      - node10LTS:
          filters:
            branches:
              ignore: gh-pages
      - node12_9:
          filters:
            branches:
              ignore: gh-pages
      - java:
          filters:
            branches:
              ignore: gh-pages
      - docs:
          filters:
            branches:
              ignore: gh-pages
      - new10LTS:
          filters:
            branches:
              ignore: gh-pages
      - new12_9:
          filters:
            branches:
              ignore: gh-pages
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
